<a href="https://colab.research.google.com/github/jeongsu1524/aipython/blob/main/2024_01_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
arr = np.arange(1, 10, 2)
print(arr)


[1 3 5 7 9]


In [6]:
ones_2d = np.ones((3, 4))
print(ones_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
arr = np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [14]:
A=np.arange(1,26).reshape(5,5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [16]:
print(A[3,3])

19


In [21]:
print(A[:2,:2])

[[1 2]
 [6 7]]


In [23]:
print(A[3:5,3:5])

[[19 20]
 [24 25]]


In [25]:
print(A[0:2,0:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [31]:
print(A[:,3:])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [34]:
B=np.arange(1,37).reshape(3,3,4)
print(B)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [36]:
BB= B.reshape(3,4,3)
print(BB)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]


In [42]:
BBB=B.flatten()
print(BBB)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
